[package]
name = "alinvoinea_secret"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.136"
serde_json = "1.0.117"
aws-sdk-secretsmanager = "1.30.0"
aws_lambda_events = "0.15.1"
lambda_runtime = "0.11.2"
